# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#  default: &default
#   adapter: sqlite3
#   encoding: unicode
#   username: nerajno
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
  

development:
  adapter: postgresql
  encoding: unicode
  database: friends_development
  pool: 5
  host: 127.0.0.1
  username: postgres
  password: sp00gy
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: friends_test
  pool: 5
  host: 127.0.0.1
  username: postgres
  password: sp00gy
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
# host: localhost
  
# production:
#   <<: *default
#   database: db/my_database_production
