<<<<<<< HEAD
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

 default: &default
  adapter: postgresql
  encoding: unicode
  username: nerajno
  pool: 5
  timeout: 5000
  

development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  pool: 5 
  username: nerajno
  password: 
  timeout: 5000

=======
development:
  adapter: postgresql
  encoding: unicode
  database: my_development_
  pool: 5
  username: nerajno
  password: 
  host: localhost
>>>>>>> bkUp4sqlite

test:
  adapter: postgresql
  encoding: unicode
<<<<<<< HEAD
  database: my_test_database
  pool: 5
  username: nerajno
  password:
  timeout: 5000
=======
  database: my_test
  pool: 5
  username: nerajno
  password: 
  host: localhost
>>>>>>> bkUp4sqlite

production:
  adapter: postgresql
  encoding: unicode
<<<<<<< HEAD
  database: my_production_database
  pool: 5
  username: nerajno
  password: 
  timeout: 5000
# host: localhost
  
# production:
#   <<: *default
#   database: db/my_database_production
=======
  database: my_production
  pool: 5
  username: nerajno
  password: 
  host: localhost
>>>>>>> bkUp4sqlite
